### PR TITLE
Clarify founding date

### PR DESCRIPTION
**Pull request by jamesray1**

### CODE REVIEW

**Comment by jamesray1** [comment]
I signed it!

**Comment by jamesray1** [comment]
Not sure why there's no confirmation.

**Comment by ALTree** [comment]
The "is an exercise for the reader" it's a joke/wink-wink to what math book authors often do, I don't think it needs to be replaced by an explanation...

**Comment by jamesray1** [comment]
Yeah I got that, but I don't really like it for a trivial detail. For maths problems it is more acceptable because the student learns more through application.

**Comment by dmitshur** [comment]
Closing because x/tour content moved to x/website (see [CL 324309](https://go.dev/cl/324309)), leaving only a few supporting Go packages. If this change still applies, it'd need to be re-sent it to x/website. Thanks.

**Pull request closed without merging**
